"use client";

import { useState, useEffect, useCallback } from "react";
import { motion } from "framer-motion";
import { Globe, ExternalLink, ArrowRight, Loader2, Compass } from "lucide-react";
import { getReports, SavedReport } from "@/lib/report-store";
import { useAuth } from "@/components/providers/AuthProvider";

interface RecentAnalysesProps {
    onViewReport: (saved: SavedReport) => void;
}

export function RecentAnalyses({ onViewReport }: RecentAnalysesProps) {
    const { user, isAuthenticated } = useAuth();
    const [recent, setRecent] = useState<SavedReport[]>([]);
    const [loading, setLoading] = useState(true);

    const fetchRecent = useCallback(async () => {
        if (!isAuthenticated) {
            setLoading(false);
            return;
        }
        setLoading(true);
        try {
            const userId = user?.email || user?.username || "anonymous";
            const all = await getReports(userId);
            setRecent(all.slice(0, 2)); // show latest 2
        } catch {
            setRecent([]);
        } finally {
            setLoading(false);
        }
    }, [user, isAuthenticated]);

    useEffect(() => { fetchRecent(); }, [fetchRecent]);

    if (loading) {
        return (
            <section>
                <div className="flex items-center justify-center py-10">
                    <Loader2 className="w-5 h-5 text-[var(--brand)] animate-spin" />
                    <span className="ml-2 text-slate-400 text-sm">Loading recent analyses...</span>
                </div>
            </section>
        );
    }

    return (
        <section>
            <div className="flex items-center justify-between mb-6">
                <h3 className="text-xl font-bold text-slate-800 dark:text-white">
                    Recent Analyses
                </h3>
                {recent.length > 0 && (
                    <button className="text-[var(--brand)] text-sm font-semibold hover:underline flex items-center gap-1 group transition-all">
                        View all history
                        <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                    </button>
                )}
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                {recent.map((saved, index) => {
                    const score = saved.report.overall_score || 0;
                    const healthColor = score >= 70 ? "bg-green-100 text-green-700" : score >= 40 ? "bg-amber-100 text-amber-700" : "bg-red-100 text-red-700";
                    const iconColor = score >= 70 ? "text-[var(--brand)]" : "text-red-500";

                    return (
                        <motion.div
                            key={saved.id}
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: 0.1 * (index + 1) }}
                            className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 overflow-hidden group hover:shadow-2xl hover:-translate-y-2 transition-all duration-300"
                        >
                            <div className="h-40 bg-slate-100 dark:bg-slate-900 flex items-center justify-center relative overflow-hidden">
                                <div className="absolute inset-0 bg-gradient-to-b from-transparent to-black/5" />
                                <div className="w-16 h-16 rounded-xl bg-white shadow-lg flex items-center justify-center p-3 z-10 transform group-hover:scale-110 transition-transform duration-500">
                                    <Globe className={`w-10 h-10 ${iconColor}`} />
                                </div>
                                <div className="absolute top-3 right-3">
                                    <span className={`${healthColor} text-[10px] font-bold px-2 py-1 rounded uppercase tracking-wider`}>
                                        Health: {score}%
                                    </span>
                                </div>
                            </div>

                            <div className="p-6">
                                <div className="mb-4">
                                    <h4 className="font-bold text-slate-800 dark:text-white text-lg leading-none truncate">
                                        {saved.report.competitor}
                                    </h4>
                                    <p className="text-slate-500 text-sm mt-1 truncate">{saved.report.niche}</p>
                                </div>
                                <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed mb-6 line-clamp-2">
                                    {saved.report.company_summary || "Competitor intelligence report generated by ContentSpy AI."}
                                </p>
                                <button
                                    onClick={() => onViewReport(saved)}
                                    className="w-full py-2.5 rounded-lg border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 font-semibold text-sm hover:bg-slate-50 dark:hover:bg-slate-700 transition-all flex items-center justify-center gap-2 active:scale-[0.98]"
                                >
                                    View Full Report
                                    <ExternalLink className="w-4 h-4" />
                                </button>
                            </div>
                        </motion.div>
                    );
                })}

                {/* CTA Card */}
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.3 }}
                    className="bg-[var(--brand)]/5 rounded-xl border border-[var(--brand)]/20 overflow-hidden flex flex-col items-center justify-center p-8 text-center group hover:shadow-2xl transition-all duration-300"
                >
                    <div className="w-16 h-16 rounded-full bg-[var(--brand)]/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                        <span className="text-[var(--brand)] text-3xl font-bold">+</span>
                    </div>
                    <h4 className="font-bold text-slate-800 dark:text-white text-lg mb-2">
                        {recent.length === 0 ? "Run Your First Analysis" : "New Analysis"}
                    </h4>
                    <p className="text-slate-500 text-sm">
                        Enter a competitor URL above to start a new analysis
                    </p>
                </motion.div>
            </div>
        </section>
    );
}
